//
//  Constants.swift
//  Camping Directory
//
//  Created by Keith Davis on 9/20/16.
//  Copyright © 2016 ZuniSoft. All rights reserved.
//

import Foundation

struct Constants {
    static let svcCampgroundURL = "http://api.amp.active.com/camping/campgrounds"
    static let svcCampgroundDetailURL = "http://api.amp.active.com/camping/campground/details"
    static let svcCampgroundAPIKey = "f7rk6put964u42x5jb32wsj4"
    
    static let stateList = ["Alabama",
                            "Alaska",
                            "Arizona",
                            "Arkansas",
                            "California",
                            "Colorado",
                            "Connecticut",
                            "Delaware",
                            "Florida",
                            "Georgia",
                            "Hawaii",
                            "Idaho",
                            "Illinois",
                            "Indiana",
                            "Iowa",
                            "Kansas",
                            "Kentucky",
                            "Louisiana",
                            "Maine",
                            "Maryland",
                            "Massachusetts",
                            "Michigan",
                            "Minnesota",
                            "Mississippi",
                            "Missouri",
                            "Montana",
                            "Nebraska",
                            "Nevada",
                            "New Hampshire",
                            "New Jersey",
                            "New Mexico",
                            "New York",
                            "North Carolina",
                            "North Dakota",
                            "Ohio",
                            "Oklahoma",
                            "Oregon",
                            "Pennsylvania",
                            "Rhode Island",
                            "South Carolina",
                            "South Dakota",
                            "Tennessee",
                            "Texas",
                            "Utah",
                            "Vermont",
                            "Virginia",
                            "Washington",
                            "West Virginia",
                            "Wisconsin",
                            "Wyoming"]
    
    static let stateDictionary = ["Alabama": "AL",
                                  "Alaska": "AK",
                                  "Arizona": "AZ",
                                  "Arkansas": "AR",
                                  "California": "CA",
                                  "Colorado": "CO",
                                  "Connecticut": "CT",
                                  "Delaware": "DE",
                                  "Florida": "FL",
                                  "Georgia": "GA",
                                  "Hawaii": "HI",
                                  "Idaho": "ID",
                                  "Illinois": "IL",
                                  "Indiana": "IN",
                                  "Iowa": "IA",
                                  "Kansas": "KS",
                                  "Kentucky": "KY",
                                  "Louisiana": "LA",
                                  "Maine": "ME",
                                  "Maryland": "MD",
                                  "Massachusetts": "MA",
                                  "Michigan": "MI",
                                  "Minnesota": "MN",
                                  "Mississippi": "MS",
                                  "Missouri": "MO",
                                  "Montana": "MT",
                                  "Nebraska": "NE",
                                  "Nevada": "NV",
                                  "New Hampshire": "NH",
                                  "New Jersey": "NJ",
                                  "New Mexico": "NM",
                                  "New York": "NY",
                                  "North Carolina": "NC",
                                  "North Dakota": "ND",
                                  "Ohio": "OH",
                                  "Oklahoma": "OK",
                                  "Oregon": "OR",
                                  "Pennsylvania": "PA",
                                  "Rhode Island": "RI",
                                  "South Carolina": "SC",
                                  "South Dakota": "SD",
                                  "Tennessee": "TN",
                                  "Texas": "TX",
                                  "Utah": "UT",
                                  "Vermont": "VT",
                                  "Virginia": "VA",
                                  "Washington": "WA",
                                  "West Virginia": "WV",
                                  "Wisconsin": "WI",
                                  "Wyoming": "WY"]
}
